name: Monitor Failed Workflows

on:
  workflow_dispatch:

jobs:
  check-failed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: List Failed Workflows in Last 6 Hours
        env:
          GH_REPO_OWNER: ${{ github.repository_owner }}
          GH_REPO_NAME: ${{ github.event.repository.name }}
        run: |
          NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          SIX_HOURS_AGO=$(date -u -d "6 hours ago" +%Y-%m-%dT%H:%M:%SZ)
          echo "Checking failed workflows between $SIX_HOURS_AGO and $NOW"
          gh run list --limit 100 --status failure --json status,conclusion,startedAt,workflowName,databaseId | \
          jq --arg SINCE "$SIX_HOURS_AGO" --arg owner "$GH_REPO_OWNER" --arg repo "$GH_REPO_NAME" '
            .[]
            | select(.startedAt > $SINCE)
            | "- \(.workflowName): https://github.com/\($owner)/\($repo)/actions/runs/\(.databaseId)"
          '
