name: Monitor Failed Workflows

on:
  workflow_dispatch:

jobs:
  check-failed:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: List Failed Workflows in Last Hour
        env:
          GH_REPO_OWNER: ${{ github.repository_owner }}
          GH_REPO_NAME: ${{ github.event.repository.name }}
        run: |
          NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          HOUR_AGO=$(date -u -d "1 hour ago" +%Y-%m-%dT%H:%M:%SZ)
