name: Submit PR using gh
on: workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo1
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Clone test2 repo using gh
        # env:
        #   GH_TOKEN: ${{ secrets.REPO2_ACCESS_TOKEN }}  
        run: gh repo clone sumabdamd/repo2
