name: Check Rate Value in JSON

on:
  workflow_dispatch:

jobs:
  check_rate_value:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read JSON and check rate value
        id: check_rate
        run: |
          # Install jq to parse JSON
          sudo apt-get install jq
          
          # Define the file you want to check (replace with the correct path if needed)
          JSON_FILE="rate/check/*.json"
          
          # Extract the 'rate' value from the JSON file
          RATE=$(jq '.rate' $JSON_FILE)
          
          # Check if the rate is more than 10
          if (( $(echo "$RATE > 10" | bc -l) )); then
            echo "Rate exceeds 10%: $RATE"
            echo "rate_exceeds=true" >> $GITHUB_ENV
          else
            echo "Rate is within limit: $RATE"
          fi

      - name: Create GitHub Issue if Rate Exceeds 10%
        if: env.rate_exceeds == 'true'
        run: |
          # Use GitHub API to create an issue
          ISSUE_TITLE="Rate Exceeds 10% in JSON File"
          ISSUE_BODY="The 'rate' value in the JSON file exceeds 10%. Please review the changes."
          ISSUE_LABEL="bug"
          
          # Make the API request to create an issue
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d @- \
            https://api.github.com/repos/${{ github.repository }}/issues <<EOF
          {
            "title": "$ISSUE_TITLE",
            "body": "$ISSUE_BODY",
            "labels": ["$ISSUE_LABEL"]
          }
          EOF
