name: Submit PR for repo2
on: workflow_dispatch
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo1
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Clone repo2 
        uses: actions/checkout@v4
        with:
          repository: "sumabdamd/repo2"
          path: repo2  
      
